dim_x: 2
dim_y: 3
dim_hid: 128
dim_lat: 128
enc_v_depth: 6
enc_qk_depth: 3
enc_pre_depth: 6
enc_post_depth: 3
dec_depth: 5
use_latent_path: True
latent_dim_mult: 1
H_A_dim: -1
use_H_A: False
use_ABLA_induce: False
num_induce: -1
H_D_init: 'xavier'
num_heads: 8
num_spin_blocks: 1